// Book list for the Verse of the Day picker. Chapter counts were read
// straight from the Bible JSON bundled with the mobile app, so the admin can
// never save a chapter the app can't resolve.

export interface BibleBook {
  id: string;
  name: string;
  nameEs: string;
  testament: "OT" | "NT";
  chapters: number;
}

export const BIBLE_BOOKS: BibleBook[] = [
  { id: "genesis", name: "Genesis", nameEs: "Génesis", testament: "OT", chapters: 50 },
  { id: "exodus", name: "Exodus", nameEs: "Éxodo", testament: "OT", chapters: 40 },
  { id: "leviticus", name: "Leviticus", nameEs: "Levítico", testament: "OT", chapters: 27 },
  { id: "numbers", name: "Numbers", nameEs: "Números", testament: "OT", chapters: 36 },
  { id: "deuteronomy", name: "Deuteronomy", nameEs: "Deuteronomio", testament: "OT", chapters: 34 },
  { id: "joshua", name: "Joshua", nameEs: "Josué", testament: "OT", chapters: 24 },
  { id: "judges", name: "Judges", nameEs: "Jueces", testament: "OT", chapters: 21 },
  { id: "ruth", name: "Ruth", nameEs: "Rut", testament: "OT", chapters: 4 },
  { id: "1-samuel", name: "1 Samuel", nameEs: "1 Samuel", testament: "OT", chapters: 31 },
  { id: "2-samuel", name: "2 Samuel", nameEs: "2 Samuel", testament: "OT", chapters: 24 },
  { id: "1-kings", name: "1 Kings", nameEs: "1 Reyes", testament: "OT", chapters: 22 },
  { id: "2-kings", name: "2 Kings", nameEs: "2 Reyes", testament: "OT", chapters: 25 },
  { id: "1-chronicles", name: "1 Chronicles", nameEs: "1 Crónicas", testament: "OT", chapters: 29 },
  { id: "2-chronicles", name: "2 Chronicles", nameEs: "2 Crónicas", testament: "OT", chapters: 36 },
  { id: "ezra", name: "Ezra", nameEs: "Esdras", testament: "OT", chapters: 10 },
  { id: "nehemiah", name: "Nehemiah", nameEs: "Nehemías", testament: "OT", chapters: 13 },
  { id: "esther", name: "Esther", nameEs: "Ester", testament: "OT", chapters: 10 },
  { id: "job", name: "Job", nameEs: "Job", testament: "OT", chapters: 42 },
  { id: "psalms", name: "Psalms", nameEs: "Salmos", testament: "OT", chapters: 150 },
  { id: "proverbs", name: "Proverbs", nameEs: "Proverbios", testament: "OT", chapters: 31 },
  { id: "ecclesiastes", name: "Ecclesiastes", nameEs: "Eclesiastés", testament: "OT", chapters: 12 },
  { id: "song-of-solomon", name: "Song of Solomon", nameEs: "Cantares", testament: "OT", chapters: 8 },
  { id: "isaiah", name: "Isaiah", nameEs: "Isaías", testament: "OT", chapters: 66 },
  { id: "jeremiah", name: "Jeremiah", nameEs: "Jeremías", testament: "OT", chapters: 52 },
  { id: "lamentations", name: "Lamentations", nameEs: "Lamentaciones", testament: "OT", chapters: 5 },
  { id: "ezekiel", name: "Ezekiel", nameEs: "Ezequiel", testament: "OT", chapters: 48 },
  { id: "daniel", name: "Daniel", nameEs: "Daniel", testament: "OT", chapters: 12 },
  { id: "hosea", name: "Hosea", nameEs: "Oseas", testament: "OT", chapters: 14 },
  { id: "joel", name: "Joel", nameEs: "Joel", testament: "OT", chapters: 3 },
  { id: "amos", name: "Amos", nameEs: "Amós", testament: "OT", chapters: 9 },
  { id: "obadiah", name: "Obadiah", nameEs: "Abdías", testament: "OT", chapters: 1 },
  { id: "jonah", name: "Jonah", nameEs: "Jonás", testament: "OT", chapters: 4 },
  { id: "micah", name: "Micah", nameEs: "Miqueas", testament: "OT", chapters: 7 },
  { id: "nahum", name: "Nahum", nameEs: "Nahúm", testament: "OT", chapters: 3 },
  { id: "habakkuk", name: "Habakkuk", nameEs: "Habacuc", testament: "OT", chapters: 3 },
  { id: "zephaniah", name: "Zephaniah", nameEs: "Sofonías", testament: "OT", chapters: 3 },
  { id: "haggai", name: "Haggai", nameEs: "Hageo", testament: "OT", chapters: 2 },
  { id: "zechariah", name: "Zechariah", nameEs: "Zacarías", testament: "OT", chapters: 14 },
  { id: "malachi", name: "Malachi", nameEs: "Malaquías", testament: "OT", chapters: 4 },
  { id: "matthew", name: "Matthew", nameEs: "Mateo", testament: "NT", chapters: 28 },
  { id: "mark", name: "Mark", nameEs: "Marcos", testament: "NT", chapters: 16 },
  { id: "luke", name: "Luke", nameEs: "Lucas", testament: "NT", chapters: 24 },
  { id: "john", name: "John", nameEs: "Juan", testament: "NT", chapters: 21 },
  { id: "acts", name: "Acts", nameEs: "Hechos", testament: "NT", chapters: 28 },
  { id: "romans", name: "Romans", nameEs: "Romanos", testament: "NT", chapters: 16 },
  { id: "1-corinthians", name: "1 Corinthians", nameEs: "1 Corintios", testament: "NT", chapters: 16 },
  { id: "2-corinthians", name: "2 Corinthians", nameEs: "2 Corintios", testament: "NT", chapters: 13 },
  { id: "galatians", name: "Galatians", nameEs: "Gálatas", testament: "NT", chapters: 6 },
  { id: "ephesians", name: "Ephesians", nameEs: "Efesios", testament: "NT", chapters: 6 },
  { id: "philippians", name: "Philippians", nameEs: "Filipenses", testament: "NT", chapters: 4 },
  { id: "colossians", name: "Colossians", nameEs: "Colosenses", testament: "NT", chapters: 4 },
  { id: "1-thessalonians", name: "1 Thessalonians", nameEs: "1 Tesalonicenses", testament: "NT", chapters: 5 },
  { id: "2-thessalonians", name: "2 Thessalonians", nameEs: "2 Tesalonicenses", testament: "NT", chapters: 3 },
  { id: "1-timothy", name: "1 Timothy", nameEs: "1 Timoteo", testament: "NT", chapters: 6 },
  { id: "2-timothy", name: "2 Timothy", nameEs: "2 Timoteo", testament: "NT", chapters: 4 },
  { id: "titus", name: "Titus", nameEs: "Tito", testament: "NT", chapters: 3 },
  { id: "philemon", name: "Philemon", nameEs: "Filemón", testament: "NT", chapters: 1 },
  { id: "hebrews", name: "Hebrews", nameEs: "Hebreos", testament: "NT", chapters: 13 },
  { id: "james", name: "James", nameEs: "Santiago", testament: "NT", chapters: 5 },
  { id: "1-peter", name: "1 Peter", nameEs: "1 Pedro", testament: "NT", chapters: 5 },
  { id: "2-peter", name: "2 Peter", nameEs: "2 Pedro", testament: "NT", chapters: 3 },
  { id: "1-john", name: "1 John", nameEs: "1 Juan", testament: "NT", chapters: 5 },
  { id: "2-john", name: "2 John", nameEs: "2 Juan", testament: "NT", chapters: 1 },
  { id: "3-john", name: "3 John", nameEs: "3 Juan", testament: "NT", chapters: 1 },
  { id: "jude", name: "Jude", nameEs: "Judas", testament: "NT", chapters: 1 },
  { id: "revelation", name: "Revelation", nameEs: "Apocalipsis", testament: "NT", chapters: 22 },
];
